// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Projeli.WikiService.Infrastructure.Database;

#nullable disable

namespace Projeli.WikiService.Api.Migrations
{
    [DbContext(typeof(WikiServiceDbContext))]
    partial class WikiServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryPage", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PagesId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "PagesId");

                    b.HasIndex("PagesId");

                    b.ToTable("CategoryPage");
                });

            modelBuilder.Entity("MemberPage", b =>
                {
                    b.Property<Guid>("EditorsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PagesId")
                        .HasColumnType("uuid");

                    b.HasKey("EditorsId", "PagesId");

                    b.HasIndex("PagesId");

                    b.ToTable("MemberPage");
                });

            modelBuilder.Entity("MemberPageVersion", b =>
                {
                    b.Property<Guid>("EditorsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PageVersionsId")
                        .HasColumnType("uuid");

                    b.HasKey("EditorsId", "PageVersionsId");

                    b.HasIndex("PageVersionsId");

                    b.ToTable("MemberPageVersion");
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WikiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WikiId", "Slug")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Permissions")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("WikiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WikiId", "UserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WikiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WikiId", "Slug")
                        .IsUnique();

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.PageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("PageVersions");
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.Wiki", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Wikis");
                });

            modelBuilder.Entity("CategoryPage", b =>
                {
                    b.HasOne("Projeli.WikiService.Domain.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeli.WikiService.Domain.Models.Page", null)
                        .WithMany()
                        .HasForeignKey("PagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemberPage", b =>
                {
                    b.HasOne("Projeli.WikiService.Domain.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("EditorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeli.WikiService.Domain.Models.Page", null)
                        .WithMany()
                        .HasForeignKey("PagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemberPageVersion", b =>
                {
                    b.HasOne("Projeli.WikiService.Domain.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("EditorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeli.WikiService.Domain.Models.PageVersion", null)
                        .WithMany()
                        .HasForeignKey("PageVersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.Category", b =>
                {
                    b.HasOne("Projeli.WikiService.Domain.Models.Wiki", "Wiki")
                        .WithMany("Categories")
                        .HasForeignKey("WikiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wiki");
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.Member", b =>
                {
                    b.HasOne("Projeli.WikiService.Domain.Models.Wiki", "Wiki")
                        .WithMany("Members")
                        .HasForeignKey("WikiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wiki");
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.Page", b =>
                {
                    b.HasOne("Projeli.WikiService.Domain.Models.Wiki", "Wiki")
                        .WithMany("Pages")
                        .HasForeignKey("WikiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wiki");
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.PageVersion", b =>
                {
                    b.HasOne("Projeli.WikiService.Domain.Models.Page", "Page")
                        .WithMany("Versions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.Page", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Projeli.WikiService.Domain.Models.Wiki", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Members");

                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
